#!/usr/bin/env bash

BIN0=$(readlink -f $0)
DIR0=$(dirname $BIN0)

RDIR=$(dirname $DIR0)

__debug() {
  if [[ "$DEBUG" == "" ]]; then
    echo -n ""
  else
    echo -e " $(ansi cyan bold)[DEBUG]$(ansi reset) $@"
  fi
}

__warn() {
  echo -e " $(ansi yellow bold)[WARN ]$(ansi reset) $@"
}

__cli_ls() {
  cd $RDIR; ls -1 | grep -v README | grep -v bin
}

__cli_new() {
  cd $RDIR

  [[ "$1" == "" ]] && __warn "provide script name" && exit 1

  D="$RDIR/$1"
  F="$RDIR/$1/$1"

  ## Create directory
  if [ ! -d "$D" ]; then
    __debug "Creating ${D}.."
    mkdir -p "$D"
  fi

  ## Create file
  if [ ! -f "$F" ]; then
    __debug "Creating ${F}.."
    echo "#!/usr/bin/env bash" > "$F"
    chmod 755 "$F"

    __debug "Creating ${D}/README.md"
    echo -e "# $1\n $1" > "${D}/README.md"
  fi
}

__cli_install() {
  TARGET="$1"
  TARGET_FILE="$RDIR/$TARGET/$TARGET"

  if [ -d $HOME/bin ]; then
    if [ ! -f $HOME/bin/$TARGET ]; then
      ln -s $TARGET_FILE $HOME/bin/$TARGET
      chmod 755 $HOME/bin/$TARGET
    else
      __warn "Link to «$TARGET» already exists"
    fi
  else
    __warn "$HOME/bin not found"
  fi
}

__cli_rm() {
  if [ -d $RDIR/$1 ]; then
    rm -rf $RDIR/$1
  fi
}

__cli_help() {
  echo " $ cli ls                    # list created scripts"
  echo " $ cli rm <scriptname>       # remove a script"
  echo " $ cli new <scriptname>      # create a script"
  echo " $ cli install <scriptname>  # create a script"
  echo " $ cli help                  # show this help"
}

case "$1" in
  "e0") $EDITOR $RDIR ;;
  "ls") cd $RDIR; __cli_ls ;;
  "rm") shift; __cli_rm $@ ;;
  "new") shift; __cli_new $@ ;;
  "install") shift; __cli_install $@ ;;
  "h"|"help") __cli_help ;;
  *) echo "TODO new+edit $1"
esac
