#!/usr/bin/env bash

BIN0=$(readlink -f $0)
DIR0=$(dirname $BIN0)
SDIR="$DIR0/jcpy"

export PYTHONPATH="$SDIR:$PYTHONPATH"

echo $PYTHONPATH

case "$1" in
"lt") 
    shift
    python3 "$SDIR/list_types.py" ${1:-$PWD}
    ;;
esac
