#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: get curl command from clipboard
#   Then store json into auth.json
#

CLIPBOARD="$(xsel -o)"

if [[ "$CLIPBOARD" != "" ]]; then
  var -i auth.curl
  var auth.curl | python3 "$PDIR/curl2json" | xsel -ib
  var -i auth.json
  var rm auth.curl
fi
