#!/usr/bin/env bash

CURL_NAME="${CURL_NAME:-shed}"
CURL_FILE="${CURL_NAME}.curl"

case "$1" in
  "auth") 
    CLIP="$(xsel -ob)"
    if [ -n "$CLIP" ]; then
      echo -ne " $(icon log info) Saving clipboard to ${CURL_FILE}.."
      echo -ne "${CLIP}" > "${CURL_FILE}"
      echo -e "done."
    fi
    ;;
  "env")
    cat ".envrc" | sed "s/^/| /"
    ;;
esac
