#!/usr/bin/env bash

BIN0=$(readlink -f $0)
DIR0=$(dirname $BIN0)
SDIR="$DIR0/ds.d"

if [[ "$1" == "ls" ]]; then
  cd $SDIR && ls -1 && cd - &>/dev/null
  exit 0
fi

if [ -f "$SDIR/$1" ]; then
  SF="$SDIR/$1"
  shift
  . "$SF" $@
fi
